deluge_clients:
  - name: "deluge-1"
    host: "192.168.0.1"
    port: 58846
    username: "user"
    password: "pass"
    per_torrent_metrics: false
  - name: "deluge-2"
    host: "192.168.0.2"
    port: 58846
    username: "user"
    password: "password"
